//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace x01.Weiqi.Model
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class DbStepEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new DbStepEntities object using the connection string found in the 'DbStepEntities' section of the application configuration file.
        /// </summary>
        public DbStepEntities() : base("name=DbStepEntities", "DbStepEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new DbStepEntities object.
        /// </summary>
        public DbStepEntities(string connectionString) : base(connectionString, "DbStepEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new DbStepEntities object.
        /// </summary>
        public DbStepEntities(EntityConnection connection) : base(connection, "DbStepEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Step> Steps
        {
            get
            {
                if ((_Steps == null))
                {
                    _Steps = base.CreateObjectSet<Step>("Steps");
                }
                return _Steps;
            }
        }
        private ObjectSet<Step> _Steps;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Steps EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSteps(Step step)
        {
            base.AddObject("Steps", step);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DbStepModel", Name="Step")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Step : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Step object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="stepContent">Initial value of the StepContent property.</param>
        public static Step CreateStep(global::System.Int32 id, global::System.String stepContent)
        {
            Step step = new Step();
            step.ID = id;
            step.StepContent = stepContent;
            return step;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String StepContent
        {
            get
            {
                return _StepContent;
            }
            set
            {
                OnStepContentChanging(value);
                ReportPropertyChanging("StepContent");
                _StepContent = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("StepContent");
                OnStepContentChanged();
            }
        }
        private global::System.String _StepContent;
        partial void OnStepContentChanging(global::System.String value);
        partial void OnStepContentChanged();

        #endregion
    
    }

    #endregion
    
}
